apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true" 
  labels:
    app: mongodb
    name: mongodb-internal
  name: mongodb-internal
  namespace: tjones-rocket
spec:
  clusterIP: "None"
  ports:
  - name: 27017-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb
  type: ClusterIP
